config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :billboards


  resources :artists do
    resources :songs
  end

  get '/billboard/:id/find_song/:id', to: 'billboards#find_song', as: 'find_song'
  patch '/billboard/:id/add_song/', to: 'billboards#add_song', as: 'add_song'
  patch '/billboard/:id/remove_song/:song_id', to: 'billboards#remove_from_bill', as: 'remove_song'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord

has_many :songs, dependent: :destroy

end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :billboard, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :find_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
    render partial: 'form'
  end
  def edit
    render partial: 'form'
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render partial: 'form'
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to artist_path(@artist)
    else
      render partial: 'form'
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private
    def artist_params
      params.require(:artist).permit(:name, :genre)
    end
    def find_artist
      @artist = Artist.find(params[:id])
    end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :find_billboard, only: [:edit, :show, :update, :destroy]

  def index
    @billboards = Billboard.all
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboard_path(@billboard)
    else
      render 'edit'
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  def find_song
    @billboard = Billboard.find(params[:id])
    @songs = Song.where('billboard_id IS ?', nil)
  end

  def add_song
    @billboard = Billboard.find(params[:id])
    @song = Song.find(params[:format])
    @song.update(billboard_id: params[:id])
    redirect_to billboard_path(@billboard)
  end

  def remove_from_bill
    @billboard = Billboard.find(params[:id])
    @song = Song.find(params[:song_id])
    @song.update(billboard_id: nil)
    redirect_to billboard_path(@billboard)
  end

  private

    def billboard_params
      params.require(:billboard).permit(:name)
    end

    def find_billboard
      @billboard = Billboard.find(params[:id])
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :find_artist

  def new
    @song = Song.new
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def edit
    render partial: 'form'
  end

  def update
    if song.update(song_params)
      redirect_to artist_path(@artist)
    else
      render :edit
    end
  end


  def destroy
  end

  private

    def find_artist
      @artist = Artist.find(params[:artist_id])
    end

    def song_params
      params.require(:song).permit(:name, :rank)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/artists/_form.html.erb
<div class="container">

 <h1><%= @artist.id? ? 'Edit' : 'Create' %></h1>

 <%= form_for @artist do |f| %>
    <div class="form-group row">
      <div class="col-xs-4">
        <%= f.label :name %>
        <%= f.text_field :name, required: true %>
      </div>
      <div class="col-xs-4">
        <%= f.label :genre %>
        <%= f.text_field :genre, required: true %>
      </div>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>

 <% if @artist.id? %>
    <%= link_to 'Cancel', artist_path(@artist) %>
  <% else %>
    <%= link_to 'Cancel', artists_path %>
  <% end %>

</div>

app/views/artists/index.html.erb
<%= render '/shared/nav' %>

<div class="ui container">

 <h1>All Artists</h1>

 <% if @artists.any? %>
    <% @artists.each do |artist| %>
    <%= link_to artist.name, artist_path(artist.id) %>
    <hr>
    <% end %>
  <% end %>

 <%= link_to 'Create New Artist', new_artist_path, class: 'btn btn-info' %>
  <%= link_to 'Back', billboards_path(@billboard), class: 'btn btn-primary' %>

</div>

app/views/artists/show.html.erb
<%= render '/shared/nav' %>


<div class="container">

 <h1>Name: <%= @artist.name %></h1>
  <h2>Genre: <%= @artist.genre %></h2>

 <% @artist.songs.each do |song| %>
    <p>
      Title: <%= song.name %>
    </p>
  <% end %>

 <%= link_to 'Add Song', new_artist_song_path(@artist) %>

 <hr>

 <%= link_to 'Back', artists_path, class: 'btn btn-primary' %>
  <%= link_to 'Edit', edit_artist_path, class: 'btn btn-info' %>
  <%= link_to 'Delete Artist', artist_path(@artist), method: :delete,
                                                              data: { confirm: 'Are you sure?'},
                                                              class: 'btn btn-danger' %>
</div>

app/views/billboards/_form.html.erb
<div class="container">


  <%= form_for @billboard, class: 'ui form' do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>

    <%= f.submit class: "ui violet basic button"  %>
  <% end %>

</div>

app/views/billboards/edit.html.erb
<%= render '/shared/nav' %>


<h1>Update <%= @billboard.name %></h1>

<%= render 'form' %>

<%= link_to "Go Back", billboard_path(@billboard), class: "btn btn-primary" %>

app/views/billboards/find_song.html.erb
<div class="container">
  <div class"ui grid">
    <h2>Pick From these Songs</h2>
    <div class "sixteen wide computer column">
      <div class="ui cards">


        <% @songs.each do |song| %>
        <div class="card">
          <div class="content">
            <div class="header">

              Track:

            </div>

            <div class="description">

              <%= song.name %>

            </div>
          </div>
          <div class="extra content">


            <%= link_to 'Add Song', add_song_path(@billboard, song),
                        method: :patch, class: "ui purple basic button" %>

          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/billboards/index.html.erb
<%= render '/shared/nav' %>
<div class="ui container billboard">
  <div>
    <h1>The Best Billboards!</h1>
  </div>

  <div class="ui grid">
    <div class="sixteen wide computer column center aligned">
      <%= link_to "Create A New Billboard Today", new_billboard_path, class: "ui blue basic button" %>
    </div>
  </div>


  <div class="ui grid">
    <% @billboards.each do |bill| %>
      <div class="sixteen wide mobile eight wide tablet four wide computer column">
        <div class="ui card billboard">

          <%= link_to bill.name, billboard_path(bill), class: "ui green button"%>
          Contribute to this list!
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/billboards/new.html.erb
<%= render '/shared/nav' %>


<div class="ui container">
  <h1>Make New Billboard</h1>

  <%= render 'form'%>

  <%= link_to 'Back to all Billboards', billboards_path, class: "ui teal basic button" %>

</div>

app/views/billboards/show.html.erb
<%= render '/shared/nav' %>


<div class="ui container">
  <h1>Welcome to <%= @billboard.name %></h1>

  <div class="ui two buttons">
    <%= link_to 'Edit Billboard', edit_billboard_path(@billboard), class: "ui teal simple button" %>
    <%= link_to 'Delete', billboard_path(@billboard), method: :delete, class: "ui red simple button" %>
  </div>

  <hr>

  <div class="ui container">
    <div class"ui grid">
      <h2>All Songs</h2>
      <div class "sixteen wide computer column">
        <div class="ui cards">
          <% @billboard.songs.each do |song| %>

          <div class="card">
            <div class="content">
              <div class="header">
                Track:
              </div>

              <div class="description">
                <%= song.name %>
              </div>
            </div>
            <div class="extra content">
              <%= link_to 'Remove From List', remove_song_path(@billboard, song), method: :patch, class: "ui orange button"  %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <hr>
   <%= link_to 'Add Song to Billboard', find_song_path, class: "ui teal button" %>
   <br>
   <%= link_to 'View Artists', artists_path, class: "ui blue button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/shared/_nav.html.erb
<div class="ui top fixed menu">
  <div class="item">
    <img src="/images/logo.png">
  </div>
  <%= link_to 'Home', root_path, class: "item"%>
  <%= link_to 'Billboards', billboards_path, class: "item"%>
  <%= link_to 'Artists', artists_path, class: "item"%>
</div>

app/views/songs/_form.html.erb
<%= render '/shared/nav' %>


<div class="container">
  <%= form_for [@artist, @song] do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
    <br>
    <%= f.label :rank %>
    <%= f.text_area :rank%>
    <%= f.submit %>
  <% end %>
</div>

app/views/songs/new.html.erb
<%= render 'form' %>

app/views/static_pages/index.html.erb
<div id="landing">
    <div class="wrapper">
      <h1 id="title">Enormo Billboards</h1>

      <%= link_to 'All billboards', billboards_path, class: "ui black basic button" %>
      <%= link_to 'View Artists', artists_path, class: "ui black basic button" %>

    </div>

</div>